export const TRASH_TYPES = {
  plastic: {
    name: "Plastic",
    icon: "♻️",
    color: "#3B82F6",
    points: 10,
    co2Saved: 0.5,
    recyclingInfo: "Clean and dry. Remove caps and labels. Place in blue recycling bin.",
  },
  paper: {
    name: "Paper",
    icon: "📄",
    color: "#8B5CF6",
    points: 8,
    co2Saved: 0.4,
    recyclingInfo: "Keep dry. Flatten boxes. Remove any plastic coating. Blue bin.",
  },
  glass: {
    name: "Glass",
    icon: "🍾",
    color: "#10B981",
    points: 12,
    co2Saved: 0.6,
    recyclingInfo: "Rinse clean. Remove lids. Separate by color if possible. Green bin.",
  },
  metal: {
    name: "Metal",
    icon: "🥫",
    color: "#6B7280",
    points: 15,
    co2Saved: 0.8,
    recyclingInfo: "Rinse aluminum and steel cans. Crush to save space. Blue bin.",
  },
  organic: {
    name: "Organic",
    icon: "🍎",
    color: "#84CC16",
    points: 5,
    co2Saved: 0.3,
    recyclingInfo: "Food scraps, yard waste. Compost or brown bin. No meat or dairy.",
  },
  electronic: {
    name: "E-Waste",
    icon: "💻",
    color: "#EF4444",
    points: 20,
    co2Saved: 1.2,
    recyclingInfo: "Take to e-waste collection point. Contains valuable materials. Never trash.",
  },
  textile: {
    name: "Textile",
    icon: "👕",
    color: "#F59E0B",
    points: 10,
    co2Saved: 0.5,
    recyclingInfo: "Donate or textile recycling bin. Clean and dry clothes and fabrics.",
  },
  battery: {
    name: "Battery",
    icon: "🔋",
    color: "#DC2626",
    points: 25,
    co2Saved: 1.5,
    recyclingInfo: "Hazardous waste. Special collection point required. Never in trash.",
  },
  general: {
    name: "General Waste",
    icon: "🗑️",
    color: "#6B7280",
    points: 2,
    co2Saved: 0.1,
    recyclingInfo: "Non-recyclable items. Regular trash bin. Consider reducing usage.",
  },
} as const;

export type TrashType = keyof typeof TRASH_TYPES;
